#端口与Session失效配置
server:
    port: 8080
    servlet:
        session:
            timeout: PT30M #30分钟

interception:
    error:
        htmlurl: '/errorPage'
        jsonStr: 'the interceptor error: type is {0}, configpoint is {1}, and configkey is {2} '


spring:
    profiles:
        active: i18n, services, journalrolemenu, emailtpl, journalconfig, articlestatus, listboard #国际化配置, 远程服务配置， 期刊菜单配置
    #---------- nacos配置--------------------------
    application:
        name: service-middle
#    cloud:
#        nacos:
#            discovery:
#                server-addr: 192.168.29.144:8848
#    #---------- nacos配置--------------------------
#    #---------- 上传文件大小限制配置--------------------------
    servlet:
        multipart:
            # 最大支持文件大小
            max-file-size: 100MB
            # 最大支持请求大小
            max-request-size: 100MB
    #---------- redis ---------------------------------------
    redis:
        host: 47.97.38.53  # IP
        port: 6379  # 端口号
        password: hanjinhao  # 密码
        timeout: 10000
        lettuce:
            pool:
                max-active: 8 # 连接池最大连接数
                max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
                min-idle: 0 # 连接池中的最小空闲连接
                max-idle: 8 # 连接池中的最大空闲连接
    thymeleaf:
        cache: false
    template: 
        cache: false


global:
    superadmin:
        email: hjhaohj@126.com
        password: hanjinhao
        firstname: han jin
    system:
        email: hjhaohj@126.com
        name: Online Journal System
    i18n: i18n.xls
    linkserver: http://112.124.55.185:8080/link/
    simialcheck:
        centerIp: http://112.124.55.185:8003
        getReportData: http://112.124.55.185:80/getReportDatas
        username: cmc@techscience.com
        password: TSPzha58699834$%
        folderId: 1870818

payment: 
    stripe: 
        publicKey: pk_test_GvF3BSyx8RSXMK5yAFhqEd3H
        apiKey: sk_test_Ou1w6LVt3zmVipDVJsvMeQsc
        webhookSecret: whsec_6

uploader:
    platform: COS #上传文件的存储平台定义，包括三种 COS,OSS,LOCAL
    cos:
        bucketName: hnajin-1306618516
        secretId: AKIDXtynLceSzHJ4YliPs4ze29zLUN1QZS5S
        secretKey: A5k9KFuJSM1QZT7VdWDeplRr1wc2C5k9
        region: ap-nanjing
    oos:
        bucketName: zhiwindrain
        accessKey: LTAI5tAy8bxW3LqpdWWxENNM
        secretKey: Qm7DHBosM6DUKj3tWztPJE3DF5YD73
        region: oss-cn-shanghai.aliyuncs.com
        dir:
    local:
        tmpdir: e:/myweb/temp/
        base: e:/myweb/base/

context:
    default-setting:
        i18n: CN


    